import type { KnowledgeCard } from "./types";

function card(
  item: Omit<KnowledgeCard, "version" | "status" | "checklist"> & Partial<Pick<KnowledgeCard, "version" | "status" | "checklist">>,
): KnowledgeCard {
  return {
    version: "v1.0",
    status: "ACTIVE",
    checklist: item.fixes.slice(0, 3),
    ...item,
  };
}

export const EMERGENCY_RISK_TYPES = ["active_fire", "active_smoke"] as const;

export function isEmergencyRisk(riskType?: string) {
  return Boolean(riskType && EMERGENCY_RISK_TYPES.includes(riskType as (typeof EMERGENCY_RISK_TYPES)[number]));
}

export const knowledgeCards: KnowledgeCard[] = [
  card({
    id: "CAMPUS-FIRE-NOW",
    source: "机关、团体、企业、事业单位消防安全管理规定",
    clause: "21",
    title: "发现明火、燃烧必须立即处置",
    text: "校园任何场所出现明火、火焰、燃烧或打火行为时，应立即熄灭火源、疏散无关人员并报告保卫处；火势扩大时拨打119。",
    domain: "紧急危险",
    zoneType: "campus",
    riskType: "active_fire",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["可见火焰 / 火苗", "打火机或点燃的物体", "燃烧的纸张、织物、垃圾"],
    negativeCues: ["仅反光或指示灯", "画面中的火焰图案而非真实火源", "已熄灭的烟头无明火"],
    keywords: ["明火", "火焰", "火苗", "燃烧", "打火", "着火", "起火", "flame", "fire", "lighter"],
    fixes: ["立即熄灭火源", "移开周边可燃物", "报告保卫处并视情况报119"],
    checklist: ["火源已熄灭", "现场已隔离", "保卫处已知悉"],
  }),
  card({
    id: "CAMPUS-SMOKE-NOW",
    source: "机关、团体、企业、事业单位消防安全管理规定",
    clause: "21",
    title: "发现烟雾或冒烟必须立即核查",
    text: "画面中出现烟雾、冒烟或疑似燃烧产物时，应按初起火灾处置：查明烟源、切断电源气源，无法控制则报警并疏散。",
    domain: "紧急危险",
    zoneType: "campus",
    riskType: "active_smoke",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["可见烟雾", "物体冒烟", "烟尘扩散"],
    negativeCues: ["雾气或蒸汽", "抽烟画面但无燃烧蔓延", "烟感探测器本身"],
    keywords: ["烟雾", "冒烟", "浓烟", "烟尘", "smoke"],
    fixes: ["查明烟源并切断电源气源", "使用灭火器或灭火毯", "无法控制则报119并疏散"],
    checklist: ["烟源已控制", "电源气源已切断", "现场可通行"],
  }),
  card({
    id: "GB-55037-4.2.1",
    source: "建筑防火通用规范",
    clause: "4.2.1",
    title: "疏散通道与安全出口应保持畅通",
    text: "疏散走道、楼梯间及安全出口应保持畅通，不得堆放影响人员安全疏散的物品。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "obstruction",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["纸箱 / 快递堆物", "安全出口标识", "有效通行宽度被占用"],
    negativeCues: ["物品位于通道边界之外", "临时搬运且有人值守", "画面为整改后空通道"],
    keywords: ["纸箱", "堆物", "快递", "走廊", "通道", "box", "carton", "corridor", "obstruction"],
    fixes: ["立即移除疏散路径内障碍物", "补拍包含安全出口标识的全景", "复核有效通行宽度不少于 1.2 米"],
    checklist: ["堆物已移除", "疏散宽度恢复", "安全出口可见", "无新增遮挡"],
    version: "v2.1",
  }),
  card({
    id: "LAB-OPS-7.3",
    source: "校级实验室安全管理办法",
    clause: "7.3",
    title: "无人值守期间不得运行高风险设备",
    text: "涉及加热、高压、高速旋转的实验设备运行期间，应安排人员现场值守并保持应急通道畅通。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "unattended",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["设备运行指示灯", "实验区无人", "加热 / 旋转设备"],
    negativeCues: ["设备处于待机", "相邻控制室有人值守", "已启用远程联锁停机"],
    keywords: ["实验室", "设备", "加热", "无人", "指示灯", "lab", "unattended"],
    fixes: ["停止无人值守设备", "核验实验审批与值守人员", "检查应急停机装置"],
    checklist: ["设备已停机", "值守记录完整", "应急通道畅通"],
    version: "v1.4",
  }),
  card({
    id: "DORM-FIRE-3.6",
    source: "学生公寓消防安全细则",
    clause: "3.6",
    title: "电动车不得进入建筑内部或占用公共走道",
    text: "电动自行车及其蓄电池不得进入宿舍楼内停放、充电，不得占用疏散走道和安全出口。",
    domain: "消防安全",
    zoneType: "dorm_lobby",
    riskType: "ebike",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["电动车轮廓", "充电线缆", "宿舍门厅 / 楼内走道"],
    negativeCues: ["车辆位于室外划线区域", "无电池的维修车", "画面为短时搬运经过"],
    keywords: ["电动车", "电瓶", "充电", "门厅", "宿舍", "ebike", "scooter"],
    fixes: ["将车辆移至室外划线停放区", "拆除违规充电线路", "复核门厅疏散净宽"],
    checklist: ["楼内无电动车", "充电线已拆除", "门厅疏散畅通"],
    version: "v3.0",
  }),
  card({
    id: "ELEC-HOLE-2.1",
    source: "教育系统重大事故隐患判定指南",
    clause: "2.1",
    title: "配电房电缆沟孔洞应封堵",
    text: "电缆沟、孔洞未采取防火封堵等防护措施的，应判定为重大事故隐患直接判定项。",
    domain: "用电安全",
    zoneType: "electrical",
    riskType: "unsealed_hole",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["电缆沟开口", "孔洞未见封堵", "配电柜周边孔缝"],
    negativeCues: ["已使用防火泥 / 阻火包封堵", "孔洞为检修中且现场封闭"],
    keywords: ["电缆沟", "孔洞", "封堵", "配电", "cable", "hole"],
    fixes: ["立即采用防火封堵材料封闭孔洞", "张贴检修警示", "复查封堵完整性"],
    checklist: ["孔洞已封堵", "防火材料到位", "警示标识完好"],
  }),
  card({
    id: "CONSTR-HARNESS-1.2",
    source: "教育系统重大事故隐患判定指南",
    clause: "1.2",
    title: "高处作业人员应正确使用安全带",
    text: "高处作业未正确佩戴或未使用安全带的，应立即制止并按重大隐患相关条款处置。",
    domain: "施工安全",
    zoneType: "construction",
    riskType: "no_harness",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["高处作业人员", "未系安全带", "临边 / 脚手架"],
    negativeCues: ["安全带已挂设在牢固点", "人员位于地面作业"],
    keywords: ["安全带", "高处", "脚手架", "临边", "harness", "scaffold"],
    fixes: ["立即停工并佩戴安全带", "检查挂点是否牢固", "补齐临边防护"],
    checklist: ["作业人员已系安全带", "挂点牢固", "临边防护连续"],
  }),
  card({
    id: "FIRE-EXT-3.1",
    source: "机关、团体、企业、事业单位消防安全管理规定",
    clause: "3.1",
    title: "灭火器、消火栓不得遮挡和挪用",
    text: "消防设施器材应设置在明显且便于取用的位置，严禁遮挡、圈占和挪用。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "extinguisher_blocked",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["灭火器箱 / 消火栓", "前方堆物", "取用路径被挡"],
    negativeCues: ["器材前方 1 米内无遮挡", "正在更换器材"],
    keywords: ["灭火器", "消火栓", "遮挡", "消防箱", "extinguisher"],
    fixes: ["清除器材前方物品", "保持取用空间", "检查器材有效期"],
    checklist: ["前方无遮挡", "器材可取用", "标识清晰"],
    version: "v1.6",
  }),
  card({
    id: "CANTEEN-GAS-2.8",
    source: "学校食堂燃气安全规范",
    clause: "2.8",
    title: "燃气阀门与报警装置周边不得遮挡",
    text: "燃气总阀、切断装置和泄漏报警器前方应保持无遮挡，并按规定完成每日闭餐检查。",
    domain: "食堂安全",
    zoneType: "canteen",
    riskType: "gas",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["燃气阀门", "报警器被挡", "闭餐后仍有火源"],
    negativeCues: ["设备已断气停用", "遮挡物位于安全距离外"],
    keywords: ["燃气", "阀门", "报警器", "后厨", "gas"],
    fixes: ["清除阀门前方物品", "测试燃气报警联动", "补录闭餐检查记录"],
    checklist: ["阀门前方无遮挡", "报警器可见", "闭餐检查已完成"],
    version: "v2.3",
  }),
  card({
    id: "ELEC-SAFE-5.4",
    source: "校园用电安全检查指引",
    clause: "5.4",
    title: "禁止插线板串联和大功率设备共用插座",
    text: "移动式插座不得串联使用，大功率电器应使用独立回路并远离可燃物。",
    domain: "用电安全",
    zoneType: "laboratory",
    riskType: "power_strip",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["插线板串联", "线缆发热变色", "周边可燃物"],
    negativeCues: ["线缆为弱电数据线", "设备总功率未超限"],
    keywords: ["插线板", "串联", "插座", "大功率"],
    fixes: ["立即停止串联用电", "核验额定功率", "清理插座周边可燃物"],
    checklist: ["串联已拆除", "独立回路使用", "周边无可燃物"],
    version: "v1.8",
  }),
  card({
    id: "PARK-EBIKE-0.1",
    source: "校园非机动车停放管理规定",
    clause: "0.1",
    title: "室外划线区域停放电动车不作为隐患",
    text: "已划线的室外非机动车停放区内停放电动车，属于合规停放，不得因“画面中出现电动车”误报。",
    domain: "交通秩序",
    zoneType: "outdoor_parking",
    riskType: "ebike_ok",
    baseLevel: "NORMAL",
    judgmentType: "hard",
    visualCues: ["室外划线车位", "非机动车停放区标识"],
    negativeCues: ["车辆进入楼内", "占用消防车道"],
    keywords: ["划线", "停车区", "室外", "parking"],
    fixes: ["无需整改"],
    checklist: ["确认位于划线区"],
  }),
  card({
    id: "GB-55037-7.1.5",
    source: "建筑防火通用规范",
    clause: "7.1.5",
    title: "安全出口不得锁闭、堵塞",
    text: "疏散门应向疏散方向开启，不得上锁、堵塞或设置影响逃生的障碍门闩。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "exit_locked",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["安全出口上锁", "铁链 / 插销", "门被桌椅顶死"],
    negativeCues: ["推闩式消防门锁可内开", "非疏散门的设备间"],
    keywords: ["安全出口", "上锁", "锁闭", "堵塞", "逃生门"],
    fixes: ["立即开启并拆除锁具", "改为推闩式逃生锁", "复核高峰时段可开启"],
  }),
  card({
    id: "GB-50016-6.5.1",
    source: "建筑设计防火规范",
    clause: "6.5.1",
    title: "常闭式防火门应保持关闭",
    text: "常闭防火门应保持关闭状态，闭门器、顺序器应完好，不得用木楔、砖块卡住常开。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "fire_door_open",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["防火门被木楔卡住", "闭门器脱落", "防火门常开"],
    negativeCues: ["常开式防火门已联动关闭", "正在搬运且有人值守"],
    keywords: ["防火门", "常闭", "闭门器", "木楔"],
    fixes: ["移除卡阻物", "修复闭门器", "恢复常闭状态"],
  }),
  card({
    id: "FIRE-CURTAIN-2.1",
    source: "建筑防火通用规范",
    clause: "6.5.3",
    title: "防火卷帘下方不得堆放物品",
    text: "防火卷帘升降范围内不得堆放货物、桌椅或其他障碍物，确保火灾时能降到位。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "curtain_blocked",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["防火卷帘导轨", "下方纸箱桌椅", "卷帘无法落地"],
    negativeCues: ["卷帘下方地面清空", "检修围挡且已停用"],
    keywords: ["防火卷帘", "卷帘门", "堆物"],
    fixes: ["清除卷帘下方物品", "测试升降", "划定禁放线"],
  }),
  card({
    id: "FIRE-LANE-1.1",
    source: "消防法",
    clause: "28",
    title: "消防车通道不得占用、堵塞",
    text: "消防车通道应保持畅通，任何单位和个人不得占用、堵塞、封闭消防车通道。",
    domain: "消防安全",
    zoneType: "gate",
    riskType: "fire_lane",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["消防车道黄线", "停放机动车", "路障锥桶长期占用"],
    negativeCues: ["临时上下客且驾驶人在场", "应急车辆作业"],
    keywords: ["消防车道", "占用", "堵塞", "停车"],
    fixes: ["立即挪车", "施划禁停标识", "复测通道净宽"],
  }),
  card({
    id: "GB-51309-3.2",
    source: "消防应急照明和疏散指示系统技术标准",
    clause: "3.2",
    title: "应急照明与疏散指示应完好点亮",
    text: "消防应急灯、疏散指示标志应保持完好有效，不得遮挡、损坏或长期熄灭。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "exit_light",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["应急灯不亮", "指示牌脱落", "标志被海报遮挡"],
    negativeCues: ["市电正常仅备电测试", "正在更换灯具"],
    keywords: ["应急灯", "疏散指示", "安全出口灯"],
    fixes: ["更换损坏灯具", "清除遮挡", "测试备用电源"],
  }),
  card({
    id: "SMOKE-DET-2.2",
    source: "火灾自动报警系统设计规范",
    clause: "6.2",
    title: "感烟探测器不得被遮挡或包裹",
    text: "探测器周围 0.5 米内不应有遮挡物，不得用塑料袋、装饰物包裹探头。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "detector_covered",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["探头套袋", "装修膜未拆除", "正下方堆到顶的货物"],
    negativeCues: ["粉尘作业临时防护且有人值守", "检修标识"],
    keywords: ["烟感", "探测器", "包裹", "遮挡"],
    fixes: ["拆除包裹物", "降低堆货高度", "测试报警"],
  }),
  card({
    id: "SPRINKLER-3.1",
    source: "自动喷水灭火系统设计规范",
    clause: "7.1",
    title: "喷淋头不得被装饰物或货物遮挡",
    text: "洒水喷头溅水盘下方净空应符合规范，货架、横幅、灯箱不得遮挡喷淋。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "sprinkler_blocked",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["喷淋头被横幅挡住", "货物顶到喷头", "喷头涂漆"],
    negativeCues: ["净空满足规范", "隐蔽式喷头面板完好"],
    keywords: ["喷淋", "喷头", "遮挡", "货架"],
    fixes: ["下调货架高度", "拆除横幅", "清洁喷头"],
  }),
  card({
    id: "STAIR-STORE-2.0",
    source: "建筑防火通用规范",
    clause: "4.2.2",
    title: "楼梯间不得作为储物空间",
    text: "封闭楼梯间、防烟楼梯间内不得堆放物品或设置影响疏散的其他使用功能。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "stair_storage",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["楼梯踏步堆物", "休息平台纸箱", "废旧家具"],
    negativeCues: ["正在清运且通道可通行"],
    keywords: ["楼梯间", "楼梯", "堆物", "储物"],
    fixes: ["立即清运", "禁止再次堆放", "张贴禁放标识"],
  }),
  card({
    id: "HYDRANT-BOX-4.1",
    source: "消防给水及消火栓系统技术规范",
    clause: "7.4",
    title: "室内消火栓箱应配件齐全可开启",
    text: "消火栓箱门不得上锁或封死，水带、水枪、阀门应齐全可见。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "hydrant_box",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["消火栓箱上锁", "箱门封死", "水带缺失"],
    negativeCues: ["箱门可随时开启", "正在更换水带"],
    keywords: ["消火栓箱", "水带", "水枪"],
    fixes: ["解除箱门锁闭", "补齐水带水枪", "测试阀门"],
  }),
  card({
    id: "DORM-HEATER-5.1",
    source: "高等学校学生宿舍消防安全管理规定",
    clause: "5.1",
    title: "宿舍禁止使用热得快等大功率违章电器",
    text: "学生宿舍严禁使用热得快、电炉、电热毯等易引发火灾的违章电器。",
    domain: "消防安全",
    zoneType: "dorm_lobby",
    riskType: "illegal_heater",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["热得快", "电炉", "床铺电热毯"],
    negativeCues: ["学校统一配置的合格饮水设备"],
    keywords: ["热得快", "电炉", "电热毯", "违章电器"],
    fixes: ["立即停用收缴", "检查线路过热痕迹", "开展宿舍用电教育"],
  }),
  card({
    id: "DORM-OPEN-FLAME-5.2",
    source: "高等学校学生宿舍消防安全管理规定",
    clause: "5.2",
    title: "宿舍内禁止吸烟和使用明火",
    text: "学生宿舍禁止吸烟、点蜡烛、焚香及使用酒精炉等明火器具。",
    domain: "消防安全",
    zoneType: "dorm_lobby",
    riskType: "open_flame",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["蜡烛", "烟头", "酒精炉", "打火机", "可见火焰"],
    negativeCues: ["应急照明误识别"],
    keywords: ["蜡烛", "吸烟", "明火", "酒精炉", "打火机", "火焰"],
    fixes: ["立即熄灭明火", "清理可燃物", "通报辅导员复查"],
  }),
  card({
    id: "DORM-WINDOW-6.3",
    source: "中小学校设计规范",
    clause: "8.1",
    title: "上人屋面及开敞外窗应有防坠落措施",
    text: "学生生活用房外窗、阳台、上人屋面应设置防坠落栏杆或限位装置。",
    domain: "防坠落",
    zoneType: "dorm_lobby",
    riskType: "fall_protection",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["阳台栏杆缺失", "外窗无限位", "护栏松动"],
    negativeCues: ["已安装限位器", "封闭式外窗"],
    keywords: ["栏杆", "防坠", "外窗", "阳台"],
    fixes: ["停止使用该区域", "补装栏杆或限位", "结构复核"],
  }),
  card({
    id: "DORM-BALCONY-3.7",
    source: "学生公寓消防安全细则",
    clause: "3.7",
    title: "阳台不得堆放易燃可燃物品",
    text: "宿舍阳台、走廊不得大量堆放纸箱、泡沫、废旧家具等可燃物。",
    domain: "消防安全",
    zoneType: "dorm_lobby",
    riskType: "balcony_fuel",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["阳台纸箱", "泡沫板", "废旧床垫"],
    negativeCues: ["少量生活用品且未堵住逃生"],
    keywords: ["阳台", "可燃物", "纸箱"],
    fixes: ["清运可燃物", "保持阳台畅通", "复查逃生窗"],
  }),
  card({
    id: "LAB-CHEM-8.1",
    source: "高等学校实验室安全规范",
    clause: "8.1",
    title: "危化品不得混放和超量存放",
    text: "氧化剂与还原剂、酸与碱等禁忌化学品应分类存放，现场不得超量存放。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "chem_mix",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["试剂混放", "超量试剂瓶", "无二次泄漏防护"],
    negativeCues: ["已按禁忌表分区", "临时领用且有人操作"],
    keywords: ["危化品", "混放", "试剂", "超量"],
    fixes: ["立即分柜存放", "设置托盘", "核销超量库存"],
  }),
  card({
    id: "LAB-CYLINDER-8.4",
    source: "气瓶安全技术规程",
    clause: "8.4",
    title: "气瓶应直立固定并戴瓶帽",
    text: "实验室气瓶应直立放置、可靠固定，空瓶与实瓶分开，乙炔瓶不得横放。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "cylinder",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["气瓶倾斜", "无铁链固定", "瓶帽缺失"],
    negativeCues: ["已用气瓶柜固定", "空瓶待运且已标识"],
    keywords: ["气瓶", "钢瓶", "乙炔", "固定"],
    fixes: ["立即扶正固定", "补戴瓶帽", "分区存放"],
  }),
  card({
    id: "LAB-FUME-7.5",
    source: "高等学校实验室安全规范",
    clause: "7.5",
    title: "挥发性实验应在开启的通风柜内进行",
    text: "产生有毒有害气体的实验应在通风柜内操作，柜门开启高度应符合要求，柜内不得当储物柜。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "fume_hood",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["通风柜关闭仍有试剂", "柜内堆满杂物", "风机未开"],
    negativeCues: ["非挥发性实验", "通风柜处于备用清洁状态"],
    keywords: ["通风柜", "通风橱", "挥发性"],
    fixes: ["开启通风", "清出杂物", "调整视窗高度"],
  }),
  card({
    id: "LAB-WASTE-9.2",
    source: "国家危险废物名录及实验室危废管理指南",
    clause: "9.2",
    title: "实验废液应密闭分类收集",
    text: "废酸、废有机溶剂等应使用专用容器密闭收集，不得敞口放置或倒入水槽。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "chem_waste",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["敞口废液桶", "水槽旁试剂瓶", "无危废标签"],
    negativeCues: ["专用密闭桶且已贴标签"],
    keywords: ["废液", "危废", "敞口"],
    fixes: ["立即密闭贴标", "分类转移暂存间", "禁止倾倒水槽"],
  }),
  card({
    id: "LAB-EYEWASH-6.2",
    source: "实验室生物安全通用要求 / 高校实验室安全检查项目",
    clause: "6.2",
    title: "洗眼器和应急喷淋不得遮挡",
    text: "洗眼器、应急喷淋装置应在危险作业点附近保持通畅，前方不得堆物，并定期放水测试。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "eyewash_blocked",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["洗眼器被纸箱挡住", "喷淋拉手被挡", "积尘未使用"],
    negativeCues: ["前方 1.5 米畅通", "刚完成放水测试"],
    keywords: ["洗眼器", "应急喷淋", "遮挡"],
    fixes: ["清除遮挡", "放水测试", "张贴定位标识"],
  }),
  card({
    id: "LAB-FRIDGE-8.7",
    source: "高等学校实验室安全规范",
    clause: "8.7",
    title: "实验室冰箱不得存放食品",
    text: "存放化学品或菌种的冰箱应专用，严禁存放食品饮料。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "lab_fridge",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["试剂冰箱内食品", "饮料瓶与试剂混放"],
    negativeCues: ["生活区独立冰箱"],
    keywords: ["冰箱", "食品", "试剂"],
    fixes: ["清出食品", "张贴专用标识", "卫生消杀"],
  }),
  card({
    id: "LAB-POISON-8.8",
    source: "危险化学品安全管理条例",
    clause: "23",
    title: "剧毒化学品柜应双人双锁",
    text: "剧毒化学品应存放在专用柜内，实行双人收发、双人双锁，柜门不得敞开。",
    domain: "实验室安全",
    zoneType: "laboratory",
    riskType: "poison_cabinet",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["剧毒柜门敞开", "钥匙留在锁上", "无双锁"],
    negativeCues: ["柜门关闭且双锁到位"],
    keywords: ["剧毒", "双人双锁", "毒害柜"],
    fixes: ["立即闭柜上锁", "核对台账", "落实双人管理"],
  }),
  card({
    id: "CANTEEN-OIL-4.3",
    source: "餐饮服务食品安全操作规范",
    clause: "4.3",
    title: "排油烟罩及油烟管道应定期清洁",
    text: "厨房排油烟设施应定期清洗，油垢不得明显积聚，防止油烟管道火灾。",
    domain: "食堂安全",
    zoneType: "canteen",
    riskType: "oil_hood",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["油烟罩厚油垢", "滤网堵塞", "周围油渍"],
    negativeCues: ["刚完成清洗且有记录"],
    keywords: ["油烟", "油垢", "排烟罩"],
    fixes: ["停灶清洗", "清理管道", "更新清洗记录"],
  }),
  card({
    id: "CANTEEN-HOSE-2.9",
    source: "城镇燃气管理条例 / 食堂燃气安全",
    clause: "2.9",
    title: "燃气连接软管不得老化破损超长",
    text: "燃气灶具连接软管应使用不锈钢波纹管或合格胶管，长度不宜过长，不得穿越墙体、窗台。",
    domain: "食堂安全",
    zoneType: "canteen",
    riskType: "gas_hose",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["胶管龟裂", "软管超长盘绕", "穿越窗户"],
    negativeCues: ["不锈钢波纹管完好"],
    keywords: ["软管", "胶管", "燃气灶"],
    fixes: ["更换合格软管", "缩短连接", "检漏"],
  }),
  card({
    id: "CANTEEN-BLANKET-3.4",
    source: "人员密集场所消防安全管理",
    clause: "3.4",
    title: "后厨应配备灭火毯并便于取用",
    text: "餐饮厨房应配备灭火毯、灭火器，放置在灶台附近且不被杂物遮挡。",
    domain: "食堂安全",
    zoneType: "canteen",
    riskType: "fire_blanket",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["无灭火毯", "灭火毯被货架挡住"],
    negativeCues: ["灭火毯悬挂可见"],
    keywords: ["灭火毯", "后厨", "灶台"],
    fixes: ["补配灭火毯", "调整悬挂位置", "培训取用"],
  }),
  card({
    id: "ELEC-BOX-5.1",
    source: "低压配电设计规范",
    clause: "7.1",
    title: "配电箱应关门上盖并保持前侧通道",
    text: "配电箱、开关柜应关闭箱门，前方应有操作通道，不得敞开带电运行或被杂物封堵。",
    domain: "用电安全",
    zoneType: "electrical",
    riskType: "open_panel",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["配电箱无盖", "箱门敞开", "前方堆物"],
    negativeCues: ["停电检修且已设围挡"],
    keywords: ["配电箱", "箱门", "无盖"],
    fixes: ["立即关门", "补装箱盖", "清空前方通道"],
  }),
  card({
    id: "ELEC-TEMP-5.6",
    source: "施工现场临时用电安全技术规范",
    clause: "5.6",
    title: "临时用电不得乱拉乱接",
    text: "临时线路应架空或穿管，不得随地拖拉、浸泡，不得钩挂金属构件。",
    domain: "用电安全",
    zoneType: "construction",
    riskType: "temp_cable",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["电线拖地", "浸泡积水", "挂钩在钢筋上"],
    negativeCues: ["已穿管架空"],
    keywords: ["临时用电", "乱拉", "拖地电线"],
    fixes: ["停电解除", "改穿管架空", "加装漏电保护"],
  }),
  card({
    id: "ELEC-WET-5.8",
    source: "校园用电安全检查指引",
    clause: "5.8",
    title: "潮湿场所用电应有防溅和漏电保护",
    text: "卫生间、开水间、地下室等潮湿场所的插座应有防溅盒，并配备漏电保护。",
    domain: "用电安全",
    zoneType: "electrical",
    riskType: "wet_power",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["潮湿插座无防溅", "积水旁插排"],
    negativeCues: ["IP44 防溅插座完好"],
    keywords: ["潮湿", "防溅", "漏电"],
    fixes: ["加装防溅盒", "排除积水", "测试漏保"],
  }),
  card({
    id: "SITE-EDGE-1.3",
    source: "教育系统重大事故隐患判定指南",
    clause: "1.3",
    title: "临边作业应设置防护栏杆",
    text: "楼层临边、屋面、阳台、基坑边等坠落风险部位应设置连续防护栏杆和挡脚板。",
    domain: "施工安全",
    zoneType: "construction",
    riskType: "edge_guard",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["临边无栏杆", "缺口", "仅拉警戒线"],
    negativeCues: ["双层栏杆连续", "已封闭洞口"],
    keywords: ["临边", "防护栏", "坠落"],
    fixes: ["立即封闭临边", "安装栏杆挡脚板", "设置警示"],
  }),
  card({
    id: "SITE-OPENING-1.4",
    source: "教育系统重大事故隐患判定指南",
    clause: "1.4",
    title: "洞口、坑槽应加盖或防护",
    text: "楼梯口、电梯井口、管道口、基坑等应设置防护盖板、栏杆或密目网，不得敞开。",
    domain: "施工安全",
    zoneType: "construction",
    riskType: "open_hole",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["洞口无盖", "电梯井敞开", "基坑无围挡"],
    negativeCues: ["盖板固定且承重足够"],
    keywords: ["洞口", "基坑", "井口", "盖板"],
    fixes: ["加盖固定", "设置栏杆", "夜间警示灯"],
  }),
  card({
    id: "SITE-SCAFFOLD-1.5",
    source: "建筑施工扣件式钢管脚手架安全技术规范",
    clause: "6.4",
    title: "脚手架应有连墙件和脚手板",
    text: "脚手架连墙件不得拆除，作业层应满铺脚手板，外侧应有密目网。",
    domain: "施工安全",
    zoneType: "construction",
    riskType: "scaffold",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["连墙件缺失", "探头板", "无密目网"],
    negativeCues: ["连墙件按间距设置"],
    keywords: ["脚手架", "连墙件", "脚手板"],
    fixes: ["停工补设连墙件", "满铺脚手板", "恢复密目网"],
  }),
  card({
    id: "SITE-HOTWORK-2.2",
    source: "机关、团体、企业、事业单位消防安全管理规定",
    clause: "20",
    title: "动火作业应审批并现场监护",
    text: "焊接、切割等动火作业应办理动火证，清除周边可燃物并设监护人、灭火器材。",
    domain: "施工安全",
    zoneType: "construction",
    riskType: "hot_work",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["焊接无监护", "周边纸箱", "无灭火器"],
    negativeCues: ["持证动火且监护人在场"],
    keywords: ["动火", "电焊", "切割"],
    fixes: ["立即停火", "办理动火证", "清理可燃物"],
  }),
  card({
    id: "CONF-SPACE-3.1",
    source: "工贸企业有限空间作业安全规定",
    clause: "8",
    title: "有限空间作业应先通风再检测后作业",
    text: "管井、化粪池、水箱等有限空间作业应设置警戒、强制通风、气体检测，严禁盲目进入。",
    domain: "有限空间",
    zoneType: "electrical",
    riskType: "confined_space",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["井口有人下井无通风", "无气体检测仪", "无监护"],
    negativeCues: ["已检测合格且强制通风"],
    keywords: ["有限空间", "下井", "化粪池", "通风"],
    fixes: ["立即撤人", "强制通风检测", "落实监护"],
  }),
  card({
    id: "MANHOLE-2.4",
    source: "城市地下管线管理 / 校园后勤安全检查",
    clause: "2.4",
    title: "检查井、污水井盖不得缺失",
    text: "校园道路、绿地内的检查井、污水井应有完好井盖，缺失或破损应立即围蔽。",
    domain: "公共安全",
    zoneType: "gate",
    riskType: "manhole",
    baseLevel: "HIGH",
    judgmentType: "hard",
    visualCues: ["井盖缺失", "破损塌陷", "无围挡"],
    negativeCues: ["已设围栏和夜间警示灯"],
    keywords: ["井盖", "污水井", "检查井"],
    fixes: ["立即围蔽", "补装井盖", "设置警示"],
  }),
  card({
    id: "GUARDRAIL-8.2",
    source: "民用建筑设计统一标准",
    clause: "6.7",
    title: "楼梯、走廊栏杆应牢固且高度合规",
    text: "中小学校、宿舍楼梯栏杆高度及立杆间距应符合防攀爬、防坠落要求，不得松动缺失。",
    domain: "防坠落",
    zoneType: "evacuation_corridor",
    riskType: "loose_rail",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["栏杆松动", "立杆缺失", "高度明显不足"],
    negativeCues: ["栏杆牢固且高度达标"],
    keywords: ["栏杆", "扶手", "松动"],
    fixes: ["封闭该段楼梯", "加固更换", "复测高度"],
  }),
  card({
    id: "FLOOR-SLIP-4.1",
    source: "校园后勤安全检查指引",
    clause: "4.1",
    title: "室内外积水湿滑应设置防滑警示",
    text: "雨雪天气、清洁作业造成的湿滑地面应及时排水并设置防滑警示标识。",
    domain: "公共安全",
    zoneType: "gate",
    riskType: "slip",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["地面积水", "无警示牌", "人员通行"],
    negativeCues: ["已设防滑垫和警示"],
    keywords: ["积水", "湿滑", "防滑"],
    fixes: ["排水清扫", "放置警示牌", "铺设防滑垫"],
  }),
  card({
    id: "AC-BRACKET-5.3",
    source: "建筑外墙附属设施安全管理",
    clause: "5.3",
    title: "空调外机支架不得严重锈蚀松动",
    text: "外墙空调外机、支架、防护栏应完好，严重锈蚀、倾斜、螺栓缺失的应立即处置。",
    domain: "高空坠物",
    zoneType: "construction",
    riskType: "ac_bracket",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["支架锈穿", "外机倾斜", "螺栓缺失"],
    negativeCues: ["支架完好有防护"],
    keywords: ["空调外机", "支架", "锈蚀"],
    fixes: ["设置警戒区", "加固或更换支架", "限制人员通行"],
  }),
  card({
    id: "WINDOW-LIMIT-8.3",
    source: "中小学校设计规范",
    clause: "8.2",
    title: "教室外窗应有开启限位",
    text: "教学用房外窗开启扇应设置限位装置，防止开启过大造成坠落风险。",
    domain: "防坠落",
    zoneType: "evacuation_corridor",
    riskType: "window_limit",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["外窗大开无限位", "限位器断裂"],
    negativeCues: ["限位完好", "固定窗"],
    keywords: ["外窗", "限位", "教室窗"],
    fixes: ["安装限位器", "限制开启角度", "检查五金件"],
  }),
  card({
    id: "SPORTS-FIX-3.2",
    source: "学校体育设施安全管理规范",
    clause: "3.2",
    title: "篮球架、球门等应锚固可靠",
    text: "移动式篮球架、足球门应配重或锚固，防止倾倒砸伤。",
    domain: "体育安全",
    zoneType: "construction",
    riskType: "sports_anchor",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["球门无配重", "篮球架轮子未锁", "地锚缺失"],
    negativeCues: ["已锚固或配重充足"],
    keywords: ["篮球架", "球门", "倾倒"],
    fixes: ["立即停止使用", "配重锚固", "锁止轮子"],
  }),
  card({
    id: "GATE-MIX-2.5",
    source: "中小学幼儿园安全防范要求",
    clause: "2.5",
    title: "校门人车混行应有隔离和值守",
    text: "校门口机动车与学生人流应物理隔离或有值守引导，上下学高峰不得失控混行。",
    domain: "交通秩序",
    zoneType: "gate",
    riskType: "mix_traffic",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["无隔离栏", "车辆穿插学生流", "无值守"],
    negativeCues: ["护栏隔离且有保安疏导"],
    keywords: ["校门", "人车混行", "高峰"],
    fixes: ["增设隔离", "增派值守", "高峰禁车"],
  }),
  card({
    id: "TREE-WIRE-4.6",
    source: "电力设施保护条例",
    clause: "10",
    title: "树木不得碰触架空电力线路",
    text: "校园架空电力线路下方树木应保持安全距离，不得搭接导线。",
    domain: "用电安全",
    zoneType: "outdoor_parking",
    riskType: "tree_wire",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["树枝搭线", "导线被压弯"],
    negativeCues: ["距离符合安全净空"],
    keywords: ["树木", "电线", "架空线"],
    fixes: ["停电或设警戒", "专业修剪", "报告供电部门"],
  }),
  card({
    id: "LIGHTNING-6.1",
    source: "建筑物防雷设计规范",
    clause: "6.1",
    title: "防雷接地装置应连接完好",
    text: "屋顶避雷带、引下线不得断裂、严重锈蚀或被拆除，接地测试应合格。",
    domain: "防雷",
    zoneType: "construction",
    riskType: "lightning",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["避雷带断裂", "引下线松开", "严重锈蚀"],
    negativeCues: ["连接完好近期检测合格"],
    keywords: ["避雷", "防雷", "接地"],
    fixes: ["修复断点", "除锈紧固", "复测接地电阻"],
  }),
  card({
    id: "STAGE-LIGHT-4.2",
    source: "演出场所消防安全管理",
    clause: "4.2",
    title: "舞台灯具悬挂应牢固并远离幕布",
    text: "礼堂、报告厅舞台灯具应可靠悬挂，与幕布、布景保持安全距离，线缆不得过载。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "stage_light",
    baseLevel: "MEDIUM",
    judgmentType: "semantic",
    visualCues: ["灯具倾斜", "贴近幕布", "线缆缠绕"],
    negativeCues: ["吊挂完好距离足够"],
    keywords: ["舞台灯", "幕布", "礼堂"],
    fixes: ["紧固吊挂", "拉开幕布距离", "检查回路"],
  }),
  card({
    id: "DIESEL-TANK-5.9",
    source: "汽车加油加气站设计与施工规范 / 后勤油库管理",
    clause: "5.9",
    title: "柴油发电机油箱周边不得有可燃物",
    text: "备用发电机及柴油桶存放点应远离火源和可燃物，配置灭火器材并保持通风。",
    domain: "消防安全",
    zoneType: "electrical",
    riskType: "diesel",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["油桶旁纸箱", "吸烟痕迹", "无灭火器"],
    negativeCues: ["专用油库且通风良好"],
    keywords: ["柴油", "油箱", "发电机"],
    fixes: ["清走可燃物", "配置灭火器", "禁止烟火"],
  }),
  card({
    id: "POOL-FENCE-3.5",
    source: "中小学幼儿园安全防范要求",
    clause: "3.5",
    title: "泳池、景观水池应有防护和值守",
    text: "校园泳池非开放时段应锁闭防护门，景观深水区应有栏杆或盖板，防止无人看管落水。",
    domain: "公共安全",
    zoneType: "gate",
    riskType: "pool_fence",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["泳池门未锁", "深水无栏杆", "无救生员"],
    negativeCues: ["已锁闭且有人值守"],
    keywords: ["泳池", "水池", "防护门"],
    fixes: ["立即锁门", "补栏杆", "落实值守"],
  }),
  card({
    id: "EXIT-OCCUPY-4.2.3",
    source: "建筑防火通用规范",
    clause: "4.2.3",
    title: "门厅、过厅不得违规改作仓库",
    text: "作为疏散路径的门厅、过厅不得隔成房间或堆放货物改变使用功能。",
    domain: "消防安全",
    zoneType: "evacuation_corridor",
    riskType: "lobby_storage",
    baseLevel: "HIGH",
    judgmentType: "semantic",
    visualCues: ["门厅隔间储物", "过厅货架"],
    negativeCues: ["临时展览且保留疏散宽度"],
    keywords: ["门厅", "过厅", "仓库"],
    fixes: ["拆除隔断", "清运货物", "恢复疏散功能"],
  }),
];
