import type { Camera, Location } from "./types";

export { knowledgeCards } from "./knowledge-cards";

export const CAMPUS_NAME = "青澜大学";

export const locations: Location[] = [
  {
    id: "loc_b2_east",
    name: "教学楼 B · 二层东侧疏散通道",
    short: "B2 东侧通道",
    building: "教学楼 B",
    floor: "2F",
    zoneType: "evacuation_corridor",
    zoneLabel: "疏散通道",
    x: 58,
    y: 34,
    cameraIds: ["cam_b2_east_01"],
    department: "保卫处",
    crowdHint: "high",
    schedule: "教学日人流密集，大课间峰值最高",
  },
  {
    id: "loc_lab_302",
    name: "实验楼 · 302 实验室",
    short: "实验室 302",
    building: "实验楼",
    floor: "3F",
    zoneType: "laboratory",
    zoneLabel: "实验室",
    x: 24,
    y: 28,
    cameraIds: ["cam_lab_302_03"],
    department: "实验室与设备管理处",
    crowdHint: "low",
    schedule: "白天有实验课值守，夜间应停机",
  },
  {
    id: "loc_dorm3",
    name: "学生公寓 3 号楼 · 门厅",
    short: "3 号楼门厅",
    building: "学生公寓 3 号楼",
    floor: "1F",
    zoneType: "dorm_lobby",
    zoneLabel: "宿舍门厅",
    x: 78,
    y: 68,
    cameraIds: ["cam_dorm3_lobby_01"],
    department: "学生处",
    crowdHint: "medium",
    schedule: "晚间回寝高峰",
  },
  {
    id: "loc_canteen",
    name: "第一食堂 · 后厨操作间",
    short: "食堂后厨",
    building: "第一食堂",
    floor: "1F",
    zoneType: "canteen",
    zoneLabel: "食堂后厨",
    x: 18,
    y: 62,
    cameraIds: ["cam_canteen_01"],
    department: "后勤处",
    crowdHint: "medium",
    schedule: "供餐期间持续作业，闭餐后应断气检查",
  },
  {
    id: "loc_elec",
    name: "教学楼 A · 配电房",
    short: "A 配电房",
    building: "教学楼 A",
    floor: "B1",
    zoneType: "electrical",
    zoneLabel: "配电房",
    x: 40,
    y: 52,
    cameraIds: ["cam_elec_a_01"],
    department: "后勤处",
    crowdHint: "low",
    schedule: "巡检点位，应保持封堵完整",
  },
  {
    id: "loc_south_gate",
    name: "南门 · 值守区",
    short: "南门值守",
    building: "南门",
    floor: "室外",
    zoneType: "gate",
    zoneLabel: "出入口",
    x: 48,
    y: 84,
    cameraIds: ["cam_gate_south_01"],
    department: "保卫处",
    crowdHint: "high",
    schedule: "全天值守",
  },
  {
    id: "loc_parking",
    name: "图书馆 · 室外划线停放区",
    short: "图书馆停车区",
    building: "图书馆",
    floor: "室外",
    zoneType: "outdoor_parking",
    zoneLabel: "室外划线区",
    x: 36,
    y: 70,
    cameraIds: ["cam_lib_park_01"],
    department: "保卫处",
    crowdHint: "medium",
    schedule: "允许在划线区域停放非机动车",
  },
  {
    id: "loc_site",
    name: "体育馆西侧 · 维修施工区",
    short: "施工临边",
    building: "体育馆",
    floor: "室外",
    zoneType: "construction",
    zoneLabel: "施工区域",
    x: 70,
    y: 18,
    cameraIds: ["cam_site_01"],
    department: "后勤处",
    crowdHint: "low",
    schedule: "维修期间应封闭并设置防护",
  },
];

export const cameras: Camera[] = [
  { id: "cam_b2_east_01", name: "B2 东侧走廊枪机", locationId: "loc_b2_east", status: "ONLINE", coverage: "安全出口与疏散走道全景", sourceType: "mock" },
  { id: "cam_lab_302_03", name: "302 实验室半球", locationId: "loc_lab_302", status: "ONLINE", coverage: "实验台与设备指示灯", sourceType: "mock" },
  { id: "cam_dorm3_lobby_01", name: "3 号楼门厅枪机", locationId: "loc_dorm3", status: "ONLINE", coverage: "门厅入口与公共走道", sourceType: "mock" },
  { id: "cam_canteen_01", name: "后厨燃气区枪机", locationId: "loc_canteen", status: "ONLINE", coverage: "燃气阀与报警器前方", sourceType: "mock" },
  { id: "cam_elec_a_01", name: "A 配电房枪机", locationId: "loc_elec", status: "ONLINE", coverage: "电缆沟与配电柜", sourceType: "mock" },
  { id: "cam_gate_south_01", name: "南门值守球机", locationId: "loc_south_gate", status: "ONLINE", coverage: "校门通道", sourceType: "mock" },
  { id: "cam_lib_park_01", name: "图书馆停车区枪机", locationId: "loc_parking", status: "ONLINE", coverage: "室外划线停放区", sourceType: "mock" },
  { id: "cam_site_01", name: "体育馆施工区枪机", locationId: "loc_site", status: "ONLINE", coverage: "临边与围挡", sourceType: "mock" },
];

export const zoneCatalog = [
  ...Array.from(
    new Map(
      locations.map((item) => [
        item.zoneType,
        { id: item.zoneType, label: item.zoneLabel, department: item.department },
      ]),
    ).values(),
  ),
  { id: "campus", label: "全校通用", department: "保卫处" },
];
